### ISSUE TITLE
Addition of Groq API Support

### ISSUE THREAD

**Issue by smasgitstudio** [MindWorkAI/AI-Studio#197]
I think Addition Of [Groq API](https://console.groq.com/) will be good for this project

because:-

Seamless integration: The Groq API uses the same syntax as OpenAI API, making it easy to integrate with the existing infrastructure.
Free access to diverse LLMs: Groq provides free access to a wide variety of high-quality LLMs, which will expand the options available to users.
Enhanced model diversity: By supporting the Groq API, you can offer the users a broader range of models to choose from, allowing them to select the best fit for their specific use cases.
Improved accessibility: This addition will make it easier for users to experiment with different models and explore various applications, promoting a more inclusive and diverse community.
Future-proofing: As the NLP landscape continues to evolve, integrating the Groq API will position well for emerging trends and developments.

**Comment by SommerEngineering** [comment]
Thank you for your suggestion @smasgitstudio. I have added Groq as a provider. It will be available with the next update to version 0.9.18. From my initial tests, I can already say: Groq is really incredibly fast 😀 .

**Comment by smasgitstudio** [comment]
thanks a lot,
